version: "3.9"

services:
  web:
    build: .
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: production
      PORT: 3030
      DB_HOST: xxxx
      DB_USER: aman_user
      DB_PASS: gcxxxxxxxxxM47c
      DB_NAME: amest_db
    # Remove volumes in production for safety
    # volumes:
    #   - .:/src
    #   - /src/node_modules
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
